name: example
description: Exemplo de implementação do dart_tefip
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  dart_tefip:
    path: ../

dev_dependencies:
  lints: ^6.0.0
